config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'questions#home', as: :home
  get 'ask', to: 'questions#ask', as: :ask
  get 'answer', to: 'questions#answer', as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end
  def answer
    @search_query = params[:query]
    return  "Great!" if @search_query == "I am going to work"
    @search_query.include?('?') ? "Silly question, get dressed and go to work!" : "I don't care, get dressed and go to work!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
  <%if @search_query == "I am going to work"%>
    return <p><%=  "Great!"  %></p>
  <%elsif @search_query.include?('?')%>
    rerurn <p><%= "Silly question, get dressed and go to work!" %></p>
  <%else%>
    return </p><%= "I don't care, get dressed and go to work!" %></p>
<%end%>
<%= link_to "ask another question", ask_path %>

app/views/questions/ask.html.erb
<p>Ask question to your coach!</p>
<form action="/answer" method="get">
  <input type="text" name="query" placeholder="Ask your coach something?" value="<%= params[:query] %>"
>
  <input type="submit">
</form>
<%= link_to "Go back", home_path %>

app/views/questions/home.html.erb
<h1>Stupid Coach!</h1>
<%= link_to "ask question", ask_path %>